image: cboettig/nonparametric-bayes
script:
  - Rscript -e 'rmarkdown::render("manuscripts/manuscript.Rmd"); rmarkdown::render("manuscripts/supplement.Rmd")'
notify:
  email:
    recipients:
      - cboettig@ropensci.org
